testGroups.push({
  name: "All mantras from Mipham Rinpoché's Le Drip Gyü Chö - Phonetics",
  sentences: true,
  phonetics: true,
  tests: [
/**/{ tibetan: "ཨོཾ་ཨཱཿཧཱུྃ།", result: "om ah hung"},
/**/{ tibetan: "ཨོཾ་ཨཱཿཧཱུྃ་སྭཱ་ཧཱ།", result: "om ah hung svaha"},
/**/{ tibetan: "ཨོཾ་ཧཱུྃ་ཏྲཱཾ་ཧྲཱིཿཨཱཿ", result: "om hung tram hrih ah"},
    { tibetan: "འཿཨཿཧཿཤཿསཿམཿ", result: "ah ah hah shah sah mah"},
/**/{ tibetan: "ཨོཾ་བཛྲ་སཏྭ་ཧཱུྃ།", result: "om vajra satva hung"},
/**/{ tibetan: "ན་མཿས་མནྟ་བུདྡྷཱ་ནཱཾ། ཨཱ་བཱི་ར་ཧཱུྃ་ཁཾ།", result: "namah samanta buddhanam    avira hung kham"},
/**/{ tibetan: "ཨོཾ་ཨཱཿཝཱི་ར་ཧཱུྃ་ཁེ་ཙ་རཿ", result: "om ahvira hung khécharah"},
/**/{ tibetan: "བྷྲཱུྃ།", result: "bhrum"},
    { tibetan: "མུ།", result: "mu"},
/**/{ tibetan: "ན་མཿསརྦ་བུདྡྷཱ་ནཱཾ་ཨཾ་མཾ།", result: "namah sarva buddhanam ang mam"},
/**/{ tibetan: "ན་མཿས་མནྟ་བུདྡྷཱ་ནཱཾ་ཨཾ།", result: "namah samanta buddhanam ang"},
    { tibetan: "ཨ།", result: "a"},
    { tibetan: "ཨོཾ་ཨ་ར་པ་ཙ་ན་དྷཱིཿ", result: "om a ra pa cha na dhih"},
    { tibetan: "ཨཱ་རོ་ལིཀ྄", result: "a ro lik"},
    { tibetan: "ཧཱུྃ་བཛྲ་བིད་སྭཱ་ཧཱ།", result: "hung vajra vid svaha"},
    { tibetan: "ཨོཾ་ཊུཾ།", result: "om trum"},
    { tibetan: "ཌཱཀྐི་ཧཱུྃ་ཛཿ", result: "drik hung jah"},
    { tibetan: "ཏྲཱཾ་བཱ་བཱ་ཊ་ཊ་ཧ་ཧ།", result: "tram vava tratra haha"},
    { tibetan: "ཨོཾ་རུ་ཊུ་རུ་ཊུ་ཧཱུྃ་ཕཊ།", result: "om rutru rutru hung phet"},
    { tibetan: "ཨོཾ་བཛྲ་ཙཀྲ་ཧཱུྃ།", result: "om vajra chakra hung"},
    { tibetan: "ཨོཾ་ག་ག་ན་སཾ་བྷ་བ་བཛྲ་པཱ་ཙ་ཧོ།", result: "om gagana sambhava vajra pacha ho"},
    { tibetan: "ཨོཾ་མཻ་ཏྲི་དྲྀཌྷ་ཙིརྟེ་ཏིཥྛ་ཧོ།", result: "om maitri dridhra chirté tishtha ho"},
    { tibetan: "ཨོཾ་ཝཱ་ཀྱེ་དཾ་ན་མཿ", result: "om vakyédam namah"},
    { tibetan: "ཨོཾ་ཨཱཿམུ་ཧཱུྃ་སྭཱ་ཧཱ།", result: "om ah mu hung svaha"},
    { tibetan: "ཨོཾ་ཨ་མྲྀ་ཏ་བིནྡུ་ཛཱ་ཝཱ་མ་ཧཱ་སུ་ཁ་སྭཱ་ཧཱ།", result: "om amrita bindu java maha sukha svaha"},
    { tibetan: "ཨོཾ་བཛྲ་པཱ་ཎི་ཧཱུྃ།", result: "om vajrapani hung"},
    { tibetan: "ཨོཾ་སྭཱཾ་ཧྲཱིཿཀཱ་ཡ་སྭཱ་ཧཱ།", result: "om svam hrih kaya svaha"},
    { tibetan: "ཨོཾ་བཛྲ་གརྦྷ་ཧཱུྃ།", result: "om vajra garbha hung"},
    { tibetan: "ཨོཾ་སརྦ་བིདྱཱ་སྭཱ་ཧཱ།", result: "om sarva vidya svaha"},
    { tibetan: "ཨོཾ་སརྦ་བིད་ཧཱུྃ།", result: "om sarva vid hung"},
    { tibetan: "ཨོཾ་ཏྲ་ཊ་ཧཱུྃ།", result: "om tratra hung"},
    { tibetan: "ཨོཾ་སརྦ་ནི་ཝ་ར་ཎ་བིཥྐཾ་བྷི་ནི་སྭཱ་ཧཱ།", result: "om sarva nivarana vishkam bhini svaha"},
    { tibetan: "ཨོཾ་ནཱི་ས་རཱ་ཡ་སྭཱ་ཧཱ།", result: "om nisaraya svaha"},
    { tibetan: "ཨོཾ་ཨཀྵ་ཧཱུྃ་ཕཊ།", result: "om aksha hung phet"},
    { tibetan: "ཨོཾ་སརྦ་མནྟ་ཎི་དཱ་ནཾ་ཀྵེ་མྃ་རྃ་ཧཱུྃ་ཀྵཿཧཿ", result: "om sarva mantani danam kshé mam ram hung kshah hah"},
    { tibetan: "ཨོཾ་ཨཱ་ཀཱ་ཤ་གརྦྷ་ཡ་སྭཱ་ཧཱ།", result: "om akashagarbhaya svaha"},
    { tibetan: "ཨོཾ་ཀྵི་ཧཿརཱ་ཛཱ་སྭཱ་ཧཱ།", result: "om kshi hah raja svaha"},
    { tibetan: "ཨོཾ་ཨཀྵ་ས་མ་ཏི་སྭཱ་ཧཱ།", result: "om aksha samati svaha"},
    { tibetan: "ཨོཾ་ག་ག་ན་གཉྫོ་གཾ་སྭཱ་ཧཱ།", result: "om gagana ganjo gam svaha"},
    { tibetan: "ཨོཾ་རཏྣ་པཱ་ཎི་ར་མུ་སྭཱ་ཧཱ།", result: "om ratnapani ramu svaha"},
    { tibetan: "ཨོཾ་སཱ་ག་ར་མ་ཏི་ས་ར་སྭཱ་ཧཱ།", result: "om sagara matisara svaha"},
    { tibetan: "ཨོཾ་རཏྣཱ་ཀཱ་རཿཧྲཱིཿརཏྣཾ་དད་སྭཱ་ཧཱ།", result: "om ratna karah hrih ratnam dad svaha"},
    { tibetan: "ཨོཾ་ས་མནྟ་བྷ་དྲ་སཾ་སྭཱ་ཧཱ།", result: "om samanta bhadra sam svaha"},
    { tibetan: "ཨོཾ་ཀྵི་ཏི་གརྦྷ་ཀྵིཾ་སྭཱ་ཧཱ།", result: "om kshitigarbha kshim svaha"},
    { tibetan: "ཨོཾ་མ་ཎི་བཛྲོ་ཧཱུྃ།", result: "om mani vajro hung"},
    { tibetan: "ཨོཾ་མ་ཎི་དྷཱ་རི་ཧཱུྃ་ཕཊ།", result: "om mani dhari hung phet"},
/**/{ tibetan: "ན་མ་སྟྲཻ་ཡ་དྷཱི་ཀཱ་ནཱཾ་ཏ་ཐཱ་ག་ཏཱ་ནཱཾ། ཨོཾ་ཨསྟ་པ་རི་བྷོ་གི་སྭཱ་ཧཱ།", result: "nama straiya dhikanam tathagatanam    om astapari bhogi svaha"},
    { tibetan: "ཨོཾ་སྭ་སྟི་ཀ་མཱ་ལཱཀྵི་བི་པུ་ལ་སཾ་བྷ་བ་དྷརྨ་དྷཱ་ཏུ་གོ་ཙ་རེ་སྭཱ་ཧཱ།", result: "om svasti kamalakshi vipula sambhava dharmadhatu gocharé svaha"},
    { tibetan: "ཨོཾ་བཛྲ་ཙཎྜ་སརྦ་དུཥྚཱན་ཏ་ཀ་ཧ་ན་ད་ཧ་པ་ཙ་ཧཱུྃ་ཕཊ།", result: "om vajra chandra sarva dushten taka hana daha pacha hung phet"},
    { tibetan: "ཨོཾ་སུཾ་བྷ་ནཾ་སུཾ་བྷ་ཧ་ར་ཙ་ར་མ་ཧཱ་པཱ་ཤ་མ་རུ་ཏ་ཨ་མོ་གྷ་བཛྲ་ས་ཏྭ་སྭཱ་ཧཱ།", result: "om sumbhanam sumbha hara chara maha pasha maruta amogha vajra satva svaha"},
    { tibetan: "ཨོཾ་མུ་ནི་མུ་ནི་སྨ་ར་སྭཱ་ཧཱ།", result: "om muni muni samara svaha"},
    { tibetan: "ཨོཾ་ཨ་ཛི་ཏཉྫ་ཡ་སརྦ་ས་ཏྭ་ས་མ་ཡ་མ་ནུ་ག་ཏ་སྭཱ་ཧཱ།", result: "om ajitenjaya sarva satva samaya manugata svaha"},
    { tibetan: "ཨོཾ་ཨཱ་ཧྲཱིཿསིཾ་ཧ་ནཱ་ད་ཧཱུྃ་ཕཊ།", result: "om a hrih simha nada hung phet"},
    { tibetan: "ཨོཾ་པདྨ་དྷཱ་རདྷཱ་ཀི་ཧཱུྃ་ཕཊ།", result: "om padma dhardhaki hung phet"},
    { tibetan: "ཨོཾ་པདྨ་ནི་ར་ཏེ་ཤྭ་ར་ཧྲཱིཿཧཱུྃ་ཕཊ།", result: "om padma nira téshvara hrih hung phet"},
    { tibetan: "ཨོཾ་རཏྣ་ཨ་གྲ་ཨ་པྲ་ཏི་ཧ་ཏ་ཧཱུྃཿཕཊ།", result: "om ratna agra aprati hata hung phet"},
    { tibetan: "ཨོཾ་ཧྲཱིཿཏྲཻ་ལོ་ཀྱ་བི་ཛ་ཡ་ཨ་མོ་གྷ་པཱ་ཤ་ཨ་པྲ་ཏི་ཧ་ཏ་ཧྲཱིཿཧ་ཧཱུྃ་ཕཊ་སྭཱ་ཧཱ།", result: "om hrih trailokya vijaya amoghapasha aprati hata hrih ha hung phet svaha"},
    { tibetan: "ཨོཾ་ཧ་ལ་ཧ་ལ་ཧྲཱིཿཔདྨ་གརྦྷ་ཧཱུྃ་ཕཊ་སྭཱ་ཧཱ།", result: "om hala hala hrih padma garbha hung phet svaha"},
    { tibetan: "ཨོཾ་པདྨ་ཨ་ལཾ་ཀཱ་ར་ཧཱུྃ་ཕཊ།", result: "om padma alamkara hung phet"},
    { tibetan: "ཨོཾ་བཛྲ་དྷརྨ་དྷཱ་ཏུ་ཧཱུྃ་སྭཱ་ཧཱ།", result: "om vajra dharmadhatu hung svaha"},
    { tibetan: "ཨོཾ་བྷྲཱུྃ་ཧྲཱིཿཧ་ཧཱུྃ་སྭཱ་ཧཱ།", result: "om bhrum hrih ha hung svaha"},
    { tibetan: "ཨོཾ་མ་ཎི་པདྨེ་ཧཱུྃ།", result: "om mani padmé hung"},
    { tibetan: "ཨོཾ་པདྨོ་ཥྞཱ་ཥ་བི་མ་ལེ་ཧཱུྃ་ཕཊ།", result: "om padmoshnisha vimalé hung phet"},
    { tibetan: "ཨོཾ་ཨ་མོ་གྷ་ཙིནྟ་མ་ཎི་པ་ར་ད་པདྨེ་ཛྭ་ལ་ཛྭ་ལ་ན་བྷུ་ཛེ་ཧཱུྃ།", result: "om amogha chinta mani parada padmé jvala jvala nabhujé hung"},
    { tibetan: "ཨོཾ་ཨ་མོ་གྷ་བཻ་རོ་ཙ་ན་མ་ཧཱ་མུ་དྲཱ་མ་ཎི་པདྨེ་ཛྭ་ལ་པྲ་བརྟ་ཡ་ཧཱུྃ།", result: "om amogha vairochana maha mudra mani padmé jvala pravartaya hung"},
    { tibetan: "ཨོཾ་ཨ་མོ་གྷ་མཎྜ་ལ་པདྨ་ཨ་བྷི་ཥེ་ཀཾ་མ་ཎི་བཛྲེ་སརྦ་ཏ་ཐཱ་ག་ཏ་ཨ་བྷི་ཥེ་ཀེ་ཧཱུྃ།", result: "om amogha mandala padma abhishékam mani vajré sarva tathagata abhishéké hung"},
    { tibetan: "ཨོཾ་ཨ་མོ་གྷ་པཱུ་ཛ་མ་ཎི་པདྨེ་བཛྲེ་ཏ་ཐཱ་ག་ཏ་བི་ལོ་ཀི་ཏེ་ས་མནྟ་པྲ་ས་ར་ཧཱུྃ།", result: "om amogha puja mani padmé vajré tathagata vilokité samanta prasara hung"},
    { tibetan: "ཏདྱ་ཐཱ། ཨོཾ་མུ་ནེ་མུ་ནེ་མ་ཧཱ་མུ་ན་ཡེ་སྭཱ་ཧཱ།", result: "tadyatha    om muné muné maha munayé svaha"},
    { tibetan: "ན་མོ་བྷ་ག་ཝ་ཏེ་སརྦ་དུརྒ་ཏི་པ་རི་ཤོ་དྷ་ན་རཱ་ཛཱ་ཡ། ཏ་ཐཱ་ག་ཏཱ་ཡ། ཨརྷ་ཏེ་སམྱཀ་སཾ་བུད་དྷཱ་ཡ། ཏདྱ་ཐཱ། ཨོཾ་ཤོ་དྷ་ནེ་ཤོ་དྷ་ནེ། སརྦ་པཱ་པཾ་བི་ཤོ་དྷ་ནེ། ཤུད་དྷེ་བི་ཤུད་དྷེ། སརྦ་ཀརྨ་ཨཱ་བ་ར་ཎ་བི་ཤུད་དྷེ་སྭཱ་ཧཱ།", result: "namo bhagawaté sarva durgati parishodhana rajaya    tathagataya    arhaté samyak sambuddhaya    tadyatha    om shodhané shodhané    sarva papam vishodhané    shuddhé vishuddhé    sarva karma avarana vishuddhé svaha"},
    { tibetan: "ཏདྱ་ཐཱ། ཨོཾ་ཤོ་དྷ་ནེ་ཤོ་དྷ་ནེ། སརྦ་པཱ་པཾ་བི་ཤོ་དྷ་ནེ། ཤུད་དྷེ་བི་ཤུད་དྷེ། སརྦ་ཀརྨ་ཨཱ་བ་ར་ཎ་བི་ཤུད་དྷེ་སྭཱ་ཧཱ།", result: "tadyatha    om shodhané shodhané    sarva papam vishodhané    shuddhé vishuddhé    sarva karma avarana vishuddhé svaha"},
    { tibetan: "ན་མོ་རཏ་ཎ་ཏྲ་ཡཱ་ཡ། ཨོཾ་ཀཾ་ཀ་ནི་ཀཾ་ཀ་ནི། རོ་ཙ་ནི་རོ་ཙ་ནི། ཏྲོ་ཊ་ནི་ཏྲོ་ཊ་ནི། ཏྲཱ་ས་ནི་ཏྲཱ་ས་ནི། པྲ་ཏི་ཧ་ན་པྲ་ཏི་ཧ་ན། སརྦ་ཀརྨ་པ་རཾ་པ་རཱ་ཎི་མེ་སརྦ་ས་ཏྭ་ནཉྩ་སྭཱ་ཧཱ།", result: "namo ratna trayaya    om kamkani kamkani    rochani rochani    trotrani trotrani    trasani trasani    pratihana pratihana    sarva karma parampara nimé sarva satva nentsa svaha"},
    { tibetan: "ན་མོ་རཏྣ་ཏྲ་ཡཱ་ཡ། ན་མོ་བྷ་ག་ཝ་ཏེ། ཨ་མི་ཏ་བྷཱ་ཡ། ཏ་ཐཱ་ག་ཏཱ་ཡ། ཨརྷ་ཏེ་སམྱཀྶཾ་བུད་དྷཱ་ཡ། ཏདྱ་ཐཱ། ཨོཾ་ཨ་མི་ཏེ། ཨ་མི་ཏཱ། ཨ་མི་ཏོད་བྷ་བེ། ཨ་མི་ཏ། སཾ་བྷ་བེ། ཨ་མི་ཏ་བི་ཀྲཱནྟེ། ཨ་མི་ཏ་བི་ཀྲཱནྟ་ག་མི་ནི། ག་ག་ན་ཀཱིརྟི་ཀ་རེ་སརྦ་ཀརྨ་ཀླེ་ཤ་ཀྵ་ཡཾ་ཀ་རི་སྭཱ་ཧཱ།", result: "namo ratna trayaya    namo bhagawaté    amitabhaya    tathagataya    arhaté samyak sambuddhaya    tadyatha    om amité    amita    amitod bhavé    amita    sambhavé    amita vikranté    amita vikranta gamini    gagana kirtikaré sarva karma klésha khayam kari svaha"},
    { tibetan: "ཨོཾ་ཨ་མི་ཏེ། ཨ་མི་ཏཱ། ཨ་མི་ཏོད་བྷ་བེ། ཨ་མི་ཏ། སཾ་བྷ་བེ། ཨ་མི་ཏ་བི་ཀྲཱནྟེ། ཨ་མི་ཏ་བི་ཀྲཱནྟ་ག་མི་ནི། ག་ག་ན་ཀཱིརྟི་ཀ་རེ་སརྦ་ཀརྨ་ཀླེ་ཤ་ཀྵ་ཡཾ་ཀ་རི་སྭཱ་ཧཱ།", result: "om amité    amita    amitod bhavé    amita    sambhavé    amita vikranté    amita vikranta gamini    gagana kirtikaré sarva karma klésha khayam kari svaha"},
    { tibetan: "ཨོཾ་རཏྣེ་རཏྣེ། མ་ཧཱ་རཏྣེ། རཏྣ་སཾ་བྷ་བེ། རཏྣ་ཀི་རཏྣེ། རཏྣ་མཱ་ལཱ། བི་ཤུད་དྷེ་ཤོདྷ་ཡ་སརྦ་པཱ་པཾ་ཧཱུྃ་ཏྲཊ།", result: "om ratné ratné    maha ratné    ratna sambhavé    ratna ki ratné    ratna mala    vishuddhé shodhaya sarva papam hung tret"},
    { tibetan: "ཨོཾ་ཨ་མོ་གྷ་ཨ་པྲ་ཏི་ཧ་ཏ། སརྦ་ཨཱ་བ་ར་ཎ། བི་ནཱ་ཤ་ནི། ཧ་ར་ཧ་ར་ཧཱུྃ་ཕཊ།", result: "om amogha aprati hata    sarva avarana    vinashani    hara hara hung phet"},
    { tibetan: "ཨོཾ་ཨ་མོ་གྷ་ཨ་པྲ་ཏི་ཧ་ཏ། སརྦ་ཨཱ་བ་ར་ཎ། བི་ཤོདྷ་ནི། ཧ་ར་ཧ་ར་ཧཱུྃ་ཕཊ།", result: "om amogha aprati hata    sarva avarana    vishodhani    hara hara hung phet"},
    { tibetan: "ཨོཾ་བཛྲ་དྷཱ་ཏཱི་ཤྭ་རཱི་སྭཱ་ཧཱ།", result: "om vajra dhati shvari svaha"},
    { tibetan: "ཨོཾ་ལོ་ཙ་ནེ་བ་སུ་དེ་སྭཱ་ཧཱ།", result: "om lochané vasudé svaha"},
    { tibetan: "ཨོཾ་པཱཎ་ཌ་རི་བཱ་སི་ནི་བ་ར་དེ་སྭཱ་ཧཱ།", result: "om pandari vasini varadé svaha"},
    { tibetan: "ཨོཾ་མཱ་མ་ཀཱི་ཀི་རི་ཀི་རི་སྭཱ་ཧཱ།", result: "om mamaki kiri kiri svaha"},
    { tibetan: "ཨོཾ་ཏཱ་རེ་ཏུཏྟཱ་རེ་ཏུ་རེ་སྭཱ་ཧཱ།", result: "om taré tuttaré turé svaha"},
    { tibetan: "ཏདྱ་ཐཱ། ཨོཾ་ཧྲཱིཿཤུ་ཏི་སྨྲྀ་ཏི་བི་ཛ་ཡེ་སྭཱ་ཧཱ། པྲཛྙཱ་པཱ་ར་མི་ཏཱ་ཡེ་སརྦ་དུརྒ་ཏི་ཤོ་དྷ་ཡ་རཱ་ཛཱ་ཡ་སྭཱ་ཧཱ།", result: "tadyatha    om hrih shuti smriti vijayé svaha    prajña paramita yé sarva durgati shodhaya rajaya svaha"},
    { tibetan: "ཨོཾ་མ་ཎི་བཛྲ་ཧྲི་ད་ཡ་བཛྲ་མཱ་ར་སིནྱ་བི་དྲ་པ་ཎི། ཧ་ན་ཧ་ན་བཛྲ་གརྦྷེ། ཏྲཱ་ས་ཡ་ཏྲཱ་ས་ཡ། སརྦ་མཱ་ར་བྷུ་བ་ནཱ་ནི་ཧཱུྃ་ཧཱུྃ། སཾ་ངྷ་ར་སཾ་དྷ་ར་བུདྡྷ་མཻ་ཏྲི་སརྦ་ཏ་ཐཱ་ག་ཏ། བཛྲ་ཀལྤ་ཨ་དྷིཥྛི་ཏེ་སྭཱ་ཧཱ།", result: "om mani vajra hridaya vajra mara sinya vidrapani    hana hana vajra garbhé    trasaya trasaya    sarva mara bhuvanani hung hung    sanghara samdhara buddha maitri sarva tathagata    vajra kalpa adishthité svaha"},
    { tibetan: "ཨོཾ་བི་པུ་ལ་གརྦྷེ། མ་ཎི་པྲ་བྷེ། ཏ་ཐཱ་ག་ཏ་ནི་རྡེ་ཤ་ནི། མ་ཎི་མ་ཎི་སུ་པྲ་བྷེ། བི་མ་ལེ། སཱ་ག་ར་གམྦྷི་རེ་ཧཱུྃ་ཧཱུྃ། ཛྭཱ་ལ་ཛྭཱ་ལ། བུདྡྷ་བི་ལོ་ཀི་ཏེ། གུ་ཧྱ་ཨ་དྷིཥྛི་ཏེ་གརྦྷེ་སྭཱ་ཧཱ།", result: "om vipula garbhé    mani prabhé    tathagata nirdé shani    mani mani suprabhé    vimalé    sagara gambhiré hung hung    jvala jvala    buddha vilokité    guhya adishthité garbhé svaha"},
    { tibetan: "ཨོཾ་པདྨ་དྷཱ་ར་ཨ་མོ་གྷ་ཛ་ཡ་ཏེ་ཙུ་རུ་ཙུ་རུ་སྭཱ་ཧཱ།", result: "om padma dhara amogha jayaté churu churu svaha"},
    { tibetan: "ཨོཾ་བྷྲཱུྃ་སྭཱ་ཧཱ། ཨོཾ་ཨ་མྲྀ་ཏ་ཨཱ་ཡུརྡ་དེ་སྭཱ་ཧཱ།", result: "om bhrum svaha    om amrita ayurdadé svaha"},
    { tibetan: "ཨོཾ་ན་མ་སྟྲཻ་ཡ་དྷཱི་ཀཱ་ནཱཾ་སརྦ་ཏ་ཐཱ་ག་ཏ་ཧྲྀ་ད་ཡ། གརྦྷེ་ཛྭ་ལ་ཛྭ་ལ་དྷརྨ་དྷཱ་ཏུ་གརྦྷེ་སཾ་བྷ་ར་མ་མ་ཨཱ་ཡུཿསཾ་ཤོ་དྷ་ཡ་སཾ་ཤོ་དྷ་ཡ། མ་མ་སརྦ་པཱ་པཾ། སརྦ་ཏ་ཐཱ་ག་ཏ་ས་མནྟོ་ཥྞཱི་ཥ་བི་མ་ལ་བི་ཤུདྡྷེ་ཧཱུྃ་ཧཱུྃ་ཧཱུྃ། ཨྃ་བྃ་སྃ་ཛཿསྭཱ་ཧཱ།", result: "om nama straiya dhikanam sarva tathagata hridaya    garbhé jvala jvala dharmadhatu garbhé sambhara mama ayuh samshodhaya samshodhaya    mama sarva papam    sarva tathagata samantoshnisha vimala vishuddhé hung hung hung    ang bam sam jah svaha"},
    { tibetan: "ཨོཾ་སརྦ་ཏ་ཐཱ་ག་ཏོཥྞི་ཥ་དྷཱ་ཏུ་མུ་དྲཱ་ཎཱི་སརྦ་ཏ་ཐཱ་ག་ཏ་དྷརྨ་དྷཱ་ཏུ་བི་བྷཱུ་ཥི་ཏ་ཨ་དྷིཥྛི་ཏེ་ཧུ་རུ་ཧུ་རུ་ཧཱུྃ་ཧཱུྃ་སྭཱ་ཧཱ།", result: "om sarva tathagatoshnisha dhatu mudrani sarva tathagata dharmadhatu vibhushita adishthité huru huru hung hung svaha"},
    { tibetan: "ཨོཾ་སརྦ་ཏ་ཐཱ་ག་ཏ་བྱཱ་ར་ལོ་ཀི་ཏེ་ཛ་ཡ་ཛ་ཡ་སྭཱ་ཧཱ། ཨོཾ་ཧུ་རུ་ཧུ་རུ་ཛ་ཡ་མུ་ཁེ་སྭཱ་ཧཱ། ཨོཾ་བཛྲ་ཨཱ་ཡུ་ཥེ་སྭཱ་ཧཱ།", result: "om sarva tathagatabya ralokité jaya jaya svaha    om huru huru jaya mukhé svaha    om vajra ayuké svaha"},
    { tibetan: "ཨོཾ་ན་མཿས་མནྟ་བུདྡྷཱ་ནཱཾ་སརྦ་བུདྡྷ་བོ་དྷི་ས་ཏྭ་ཧྲྀ་ད་ཡཾ་ནི་བི་ཤ་ནི་ནི་མཿ སརྦ་བིརྱཱ་སྭཱ་ཧཱ།", result: "om namah samanta buddhanam sarva buddha bodhisatva hridayam nivisha ninimah    sarva virya svaha"},
    { tibetan: "ན་མཿསརྦ་ཏ་ཐཱ་ག་ཏ་ཧྲྀ་ད་ཡ་ཨ་ནུ་ག་ཏེ། ཨོཾ་ཀུ་རུཾ་གི་ནི་སྭཱ་ཧཱ།", result: "namah sarva tathagata hridaya anugaté    om kurum gini svaha"},
    { tibetan: "ཨོཾ་ཨཱཿལི་ཀཱ་ལི་ཛྙཱ་ན་པཉྩ་སཏྭ་ཀྲོ་ཏ་མུ་ན་ཡེ་སྭཱ་ཧཱ།", result: "om ahli kali gyana pancha satva krota munayé svaha"},
    { tibetan: "ཨོཾ་ཨཱཿཧཱུྃ་བཛྲ་མ་ཧཱ་གུ་རུ་སརྦ་སིདྡྷི་ཧཱུྃ༔", result: "om ah hung vajra maha guru sarva siddhi hung"},
    { tibetan: "ཨོཾ་བྷོ་དྷི་ཙིཏྟ་མ་ཧཱ་སུ་ཁ་ཛྙཱ་ན་དྷཱ་ཏུ་ཨཱཿ", result: "om bhodhicitta maha sukha gyana dhatu ah"},
    { tibetan: "ཨོཾ་རུ་ལུ་རུ་ལུ་ཧཱུཾ་བྷྱོ་ཧཱུྃ།", result: "om rulu rulu hung jo hung"},
    { tibetan: "ཨ་ཧ་རི་ནི་ས་ཧཱུྃ།", result: "a harinisa hung"},
    { tibetan: "ཨོཾ་ཨཱཿཔྲཛྙཱ་དྷྲྀ་ཀ་ཧཱ་ཧཱུྃ།", result: "om ah prajña dhrika ha hung"},
    { tibetan: "ཨོཾ་ཨཱཿཧཱུྃ་ཧྲཱིཿ ཨོཾ་མ་ཎི་པདྨེ་ཧཱུྃ། ཨོཾ་བཻ་རོ་ཙ་ན་ཧཱུྃ་ཨཀྵོ་བྷྱ། རཏྣ་སམྦྷ་ཝཿ ཨ་མི་དྷེ་ཝཿཨ་མོ་གྷ་སིདྡྷི་ཧཱུྃ། ཨོཾ་པདྨ་ཧསྟ་མ་ཧཱ་ཨ་མོ་གྷ་པཱ་ཤ་སཱ་དྷ་ཡ་ས་མ་ཡ་ཧྲྀ་ད་ཡཱཾ་ཙ་ར་ཙ་ར་ཧཱུྃ༔ ན་མོ་བྷ་ག་ཝ་ཏེ་ཨཱརྱ་ཨ་ཝ་ལོ་ཀི་ཏེ་ཤྭ་རཱ་ཡ། བོ་དྷི་སཏྭ་ཡ་མ་ཧཱ་སཏྭ་ཡ་མ་ཧཱ་ཀ་རུ་ཎི་ཀཱ་ཡ༔ སིདྡྷི་མནྟྲ་ཡ་ཡ་ནི་སྭཱ་ཧཱ།", result: "om ah hung hrih    om mani padmé hung    om vairochana hung akshobhya    ratna sambhavah    amidhévah amogha siddhi hung    om padma hasta maha amoghapasha sadhaya samaya hridayam chara chara hung    namo bhagawaté arya avalokiteshvaraya    bodhisatvaya mahasatvaya maha karunikaya    siddhi mantraya yani svaha"},
    { tibetan: "ན་མ་སྟྲཻ་ཡ་དྷཱི་ཀཱ་ནཱཾ་སརྦ་ཏ་ཐཱ་ག་ཏེ་བྷྱཿ ཨརྷ་ཏེ་བྷྱཿ སམྱ་ཀྶཾ་བུདྡྷེ་བྷྱཿ ཏདྱ་ཐཱ། ཨོཾ་ཀུ་མ་རཱུ་བི་དྷཱ་ར་ཎཱི། བི་ཤྭ་སཾ་བྷ་བ། ཨཱ་གཙྪ་ཨཱ་གཙྪ། ལ་ཧུ་ལ་ཧུ། བྷྲཱུྃ་བྷྲཱུྃ། ཧཱུྃ་ཧཱུྃ། ཛི་ན་ཛིཀ །མཉྫུ་ཤྲཱི་ཡེ། སུ་ཤྲཱི་ཡེ། ཏཱ་ར་ཡ་མཱྃ། སརྦ་དུ་ཁེ་བྷྱཿཕཊ་ཕཊ། ཤ་མ་ཡ་ཤ་མ་ཡ། ཨམྲྀ་ཏོདྦྷ་བ། ཨུ་ཏ་བྷ་ཝེ། སརྦ་པཱ་པཾ་མེ་ནཱ་ཤ་ཡ་སྭཱ་ཧཱ།", result: "nama straiya dhikanam sarva tathagaté jah    arhaté jah    samyak sambuddhé jah    tadyatha    om kumaru vidharani    vishva sambhava    agancha agancha    lahu lahu    bhrum bhrum    hung hung    jina jik    manjushriyé    sushriyé    tarayamam    sarva dukhé jah phet phet    shamaya shamaya    amritod bhava    utabhavé    sarva papam ménashaya svaha"},
    { tibetan: "ན་མ་སྟྲཻ་ཡ་དྷཱི་ཀཱ་ནཱཾ་ཏ་ཐཱ་ག་ཏཱ་ནཱཾ་སརྦ་ཏྲཱ་པྲ་ཏི་ཧ་ཏཱ་བཱ་པྟི། དྷརྨ་ཏཱ་བཱ་སི་ནཱཾ། ཨཾ་ཨ། ས་མ་ས་མ་ས་མནྟ་ཏོ། ཨཱ་ནནྟཱ་པཱ་པྟི་ཤཱ་ས་ནི་ཧ་ར་ཧ་ར་སྨ་ར་སྨ་ར་ཎི་བི་ག་ཏ་རཱ་ག་བུད་དྷ་དྷརྨ་ཏེ། ས་ར་ས་ར་ས་མ་བ་ལ་ཧ་ས་ཧ་ས། ཏྲ་ཡ་ཏྲ་ཡ། ག་ག་ན་མ་ཧཱ་བ་ར་ཎ་ལ་ཀྵ་ཎེ་ཛྭཱ་ལ་ཛྭཱ་ལ་ན་སཱ་ག་རེ་སྭཱ་ཧཱ།", result: "nama straiya dhikanam tathagatanam sarva traprati hata vapti    dharmata vasinam    ang a    sama sama samantato    ananta papti shasani hara hara samara samara nivi gata raga buddha dharmaté    sara sara samavala hasa hasa    traya traya    gagana maha varana lakshané jvala jvalana sagaré svaha"},
    { tibetan: "ན་མཿསརྦ་བུདྡྷ་བོ་དྷི་ས་ཏྭཱ་ནཱཾ་པ་ར་པ་ར། སརྦཾ་སརྦཾ། ས་མ་ས་མ། ཀཱ་རུ་ཎཱཾ་ཀཱ་རུ་ཎཱཾ། ཏཱ་རཱ་ཏཱ་རཱ། སཱ་རཱ་སཱ་རཱ། ཨ་ཏཱི་ཨ་ཏཱི། ཨཱ་མཱི་ཏཱཾ་ཨཱ་མཱི་ཏཱཾ། ཨ་ཏཱི་ཨ་ཏཱི། བཱི་རཱཾ་བཱི་རཱཾ། ཨཱ་ཏཱི་ཨཱ་ཏཱི། ཤཱུ་རཾ་ཤཱུ་རཾ། ཧ་ཧ་ཧ་ཧ། མ་ཧཱ་ས་མ་ཡ། ན་མཿཏྲ། ཨ་མ་ལ་སིདྡྷི་དཱ་ཡ་ཀེ་བྷྱཿ སརྦ་བུ་དྡྷ་བོ་དྷི་ས་ཏྭ་བྷྱཿ སརྦ་ཨ་ནནྟ་མ། དྷྱེ་བྷྱཿམ་ཧཱ་ཀཱ་རུ་ཎཱི། མཱ་ལཱི་ནཱི། ཏྲི་ས་མ་ཡེ་ཛྭ་ལ་སྭཱ་ཧཱ།", result: "namah sarva buddha bodhisatvanam para para    sarvam sarvam    sama sama    karunam karunam    tara tara    sara sara    ati ati    amitam amitam    ati ati    viram viram    ati ati    shuram shuram    haha haha    maha samaya    namah tra    amala siddhi dayaké jah    sarva buddha bodhisatva jah    sarva anantama    dhyé jah maha karuni    malini    tri samayé jvala svaha"},
    { tibetan: "ཨོཾ་བཛྲ་སཏྭ་ས་མ་ཡ་མ་ནུ་པཱ་ལ་ཡ། བཛྲ་ས་ཏྭ་ཏྭེ་ནོ་པ་ཏིཥྛ་དྲྀ་ཌྷོ་མེ་བྷ་ཝ། སུ་ཏོ་ཥྱོ་མེ་བྷ་ཝ། ཨ་ནུ་རཀྟོ་མེ་བྷ་ཝ། སུ་པོ་ཥྱོ་མེ་བྷ་ཝ། སརྦ་སིདྡྷི་མྨེ་པྲ་ཡཙྪ། སརྦ་ཀརྨ་སུ་ཙ་མེ། ཙིཏྟཾ་ཤྲེ་ཡཿཀུ་རུ་ཧཱུྃ། ཧ་ཧ་ཧ་ཧ་ཧོ། བྷ་ག་ཝཱན། སརྦ་ཏ་ཐཱ་ག་ཏ། བཛྲ་མ་མེ་མུཉྩ། བཛྲཱི་བྷ་ཝ་མ་ཧཱ་ས་མ་ཡ་སཏྭ་ཨཱ།", result: "om vajra satva samaya manupalaya    vajra satva tvénopa tishtha dridho mébhava    sutoshyo mébhava    anu rakto mébhava    suposhyo mébhava    sarva siddhi mépra yacha    sarva karma suchamé    chittam shré yah kuru hung    haha haha ho    bhagavan    sarva tathagata    vajra mamé muncha    vajri bhava maha samaya satva a"},
    { tibetan: "ཨོཾ་ཨ་ཨཱ་ཨི་ཨཱི་ཨུ་ཨཱུ་རྀ་རཱྀ་ལྀ་ལཱྀ་ཨེ་ཨཻ་ཨོ་ཨཽ་ཨཾ་ཨཿསྭཱ་ཧཱ།", result: "om a a i i u u ri ri li li é ai o au ang ah svaha"},
    { tibetan: "ཨོཾ་ཀ་ཁ་ག་གྷ་ང༌། ཙ་ཚ་ཛ་ཛྙ་ཉ། ཊ་ཋ་ཌ་ཌྷ་ཎ། ཏ་ཐ་ད་དྷ་ན། པ་ཕ་བ་བྷ་མ། ཡ་ར་ལ་ཝ། ཤ་ཥ་ས་ཧ་ཀྵ་སྭཱ་ཧཱ།", result: "om ka kha ga gha nga    cha ch'a ja gya nya    tra thra dra dhra na    ta tha da dha na    pa pha ba bha ma    ya ra la va    sha sha sa ha ksha svaha"},
    { tibetan: "ཨོཾ་ཡེ་དྷརྨྨ་ཧེ་ཏུ་པྲ་བྷ་ཝཱ་ཧེ་ཏུནྟེ་ཥཱནྟ་ཐཱ་ག་ཏོ་ཧྱ་ཝ་དཏ། ཏེ་ཥཱཉྩ་ཡོ་ནི་རོ་དྷ་ཨེ་ཝཾ་བཱ་དཱི་མ་ཧཱ་ཤྲ་མ་ཎཿསྭཱ་ཧཱ།", result: "om yé dharma hétu prabhava hétun téshan tathagato hayavadet    téshenchayo nirodha évam vadi maha shramanah svaha"},
  ]
})