testGroups.push({
    name: "All mantras from Mipham Rinpoché's Le Drip Gyü Chö",
    sentences: true,
    tests: [
/**/{ tibetan: "ཨོཾ་ཨཱཿཧཱུྃ།", transliteration: "oṁ āḥ hūṁ"},
/**/{ tibetan: "ཨོཾ་ཨཱཿཧཱུྃ་སྭཱ་ཧཱ།", transliteration: "oṁ āḥ hūṁ svāhā"},
/**/{ tibetan: "ཨོཾ་ཧཱུྃ་ཏྲཱཾ་ཧྲཱིཿཨཱཿ", transliteration: "oṁ hūṁ trāṁ hrīḥ āḥ"},
    { tibetan: "འཿཨཿཧཿཤཿསཿམཿ", transliteration: "āḥ aḥ haḥ śaḥ saḥ maḥ"},
/**/{ tibetan: "ཨོཾ་བཛྲ་སཏྭ་ཧཱུྃ།", transliteration: "oṁ vajra satva hūṁ"},
/**/{ tibetan: "ན་མཿས་མནྟ་བུདྡྷཱ་ནཱཾ། ཨཱ་བཱི་ར་ཧཱུྃ་ཁཾ།", transliteration: "namaḥ samanta buddhānāṁ    ābīra hūṁ khaṁ"},
/**/{ tibetan: "ཨོཾ་ཨཱཿཝཱི་ར་ཧཱུྃ་ཁེ་ཙ་རཿ", transliteration: "oṁ āḥvīra hūṁ khécaraḥ"},
/**/{ tibetan: "བྷྲཱུྃ།", transliteration: "bhrūṁ"},
    { tibetan: "མུ།", transliteration: "mu"},
/**/{ tibetan: "ན་མཿསརྦ་བུདྡྷཱ་ནཱཾ་ཨཾ་མཾ།", transliteration: "namaḥ sarva buddhānāṁ aṁ maṁ"},
/**/{ tibetan: "ན་མཿས་མནྟ་བུདྡྷཱ་ནཱཾ་ཨཾ།", transliteration: "namaḥ samanta buddhānāṁ aṁ"},
    { tibetan: "ཨ།", transliteration: "a"},
    { tibetan: "ཨོཾ་ཨ་ར་པ་ཙ་ན་དྷཱིཿ", transliteration: "oṁ a ra pa tsa na dhīḥ"},
    { tibetan: "ཨཱ་རོ་ལིཀ྄", transliteration: "ā ro lik"},
    { tibetan: "ཧཱུྃ་བཛྲ་བིད་སྭཱ་ཧཱ།", transliteration: "hūṁ vajra bi svāhā"},
    { tibetan: "ཨོཾ་ཊུཾ།", transliteration: "oṁ ṭuṁ"},
    { tibetan: "ཌཱཀྐི་ཧཱུྃ་ཛཿ", transliteration: "ḍīk hūṁ jaḥ", phonetics: "drik hung dza"},
    { tibetan: "ཏྲཱཾ་བཱ་བཱ་ཊ་ཊ་ཧ་ཧ།", transliteration: "trāṁ bābā ṭaṭa haha"},
    { tibetan: "ཨོཾ་རུ་ཊུ་རུ་ཊུ་ཧཱུྃ་ཕཊ།", transliteration: "oṁ ruṭu ruṭu hūṁ phaṭ", phonetics: "om rutru rutru hung phet"},
    { tibetan: "ཨོཾ་བཛྲ་ཙཀྲ་ཧཱུྃ།", transliteration: "oṁ vajra cakra hūṁ", phonetics: "om vajra chakra hung"},
    { tibetan: "ཨོཾ་ག་ག་ན་སཾ་བྷ་བ་བཛྲ་པཱ་ཙ་ཧོ།", transliteration: "oṁ gagana saṁbhawa vajra pātsa ho"},
    { tibetan: "ཨོཾ་མཻ་ཏྲི་དྲྀཌྷ་ཙིརྟེ་ཏིཥྛ་ཧོ།", transliteration: "oṁ maitri dṛḍha tsirté tiṣṭha ho", phonetics: "om maitri dridha tsirté tishta ho"},
    { tibetan: "ཨོཾ་ཝཱ་ཀྱེ་དཾ་ན་མཿ", transliteration: "oṁ wākyédaṁ namaḥ"},
    { tibetan: "ཨོཾ་ཨཱཿམུ་ཧཱུྃ་སྭཱ་ཧཱ།", transliteration: "oṁ āḥ mu hūṁ svāhā"},
    { tibetan: "ཨོཾ་ཨ་མྲྀ་ཏ་བིནྡུ་ཛཱ་ཝཱ་མ་ཧཱ་སུ་ཁ་སྭཱ་ཧཱ།", transliteration: "oṁ amṛta bindu jā wā mahā sukha svāhā", phonetics: "om amrita bindu dzawa maha sukha soha"},
    { tibetan: "ཨོཾ་བཛྲ་པཱ་ཎི་ཧཱུྃ།", transliteration: "oṁ vajrapāṇi hūṁ"},
    { tibetan: "ཨོཾ་སྭཱཾ་ཧྲཱིཿཀཱ་ཡ་སྭཱ་ཧཱ།", transliteration: "oṁ svāṁ hrīḥ kāya svāhā"},
    { tibetan: "ཨོཾ་བཛྲ་གརྦྷ་ཧཱུྃ།", transliteration: "oṁ vajra garbha hūṁ"},
    { tibetan: "ཨོཾ་སརྦ་བིདྱཱ་སྭཱ་ཧཱ།", transliteration: "oṁ sarva bidyā svāhā"},
    { tibetan: "ཨོཾ་སརྦ་བིད་ཧཱུྃ།", transliteration: "oṁ sarva bité hūṁ"},
    { tibetan: "ཨོཾ་ཏྲ་ཊ་ཧཱུྃ།", transliteration: "oṁ traṭa hūṁ"},
    { tibetan: "ཨོཾ་སརྦ་ནི་ཝ་ར་ཎ་བིཥྐཾ་བྷི་ནི་སྭཱ་ཧཱ།", transliteration: "oṁ sarva niwaraṇa biṣkaṁ bhini svāhā"},
    { tibetan: "ཨོཾ་ནཱི་ས་རཱ་ཡ་སྭཱ་ཧཱ།", transliteration: "oṁ nīsarāya svāhā"},
    { tibetan: "ཨོཾ་ཨཀྵ་ཧཱུྃ་ཕཊ།", transliteration: "oṁ akṣa hūṁ phaṭ", phonetics: "om akṣa hung phet"},
    { tibetan: "ཨོཾ་སརྦ་མནྟ་ཎི་དཱ་ནཾ་ཀྵེ་མྃ་རྃ་ཧཱུྃ་ཀྵཿཧཿ", transliteration: "oṁ sarva mantaṇi dānaṁ khyé maṁ raṁ hūṁ khyaḥ haḥ"},
    { tibetan: "ཨོཾ་ཨཱ་ཀཱ་ཤ་གརྦྷ་ཡ་སྭཱ་ཧཱ།", transliteration: "oṁ ākāśagarbhaya svāhā"},
    { tibetan: "ཨོཾ་ཀྵི་ཧཿརཱ་ཛཱ་སྭཱ་ཧཱ།", transliteration: "oṁ kṣi haḥ rājā svāhā", phonetics: "om kshi ha radza soha"},
    { tibetan: "ཨོཾ་ཨཀྵ་ས་མ་ཏི་སྭཱ་ཧཱ།", transliteration: "oṁ akṣa samati svāhā"},
    { tibetan: "ཨོཾ་ག་ག་ན་གཉྫོ་གཾ་སྭཱ་ཧཱ།", transliteration: "oṁ gagana gandzo gaṁ svāhā"},
    { tibetan: "ཨོཾ་རཏྣ་པཱ་ཎི་ར་མུ་སྭཱ་ཧཱ།", transliteration: "oṁ ratnapāṇi ramu svāhā"},
    { tibetan: "ཨོཾ་སཱ་ག་ར་མ་ཏི་ས་ར་སྭཱ་ཧཱ།", transliteration: "oṁ sāgara matisara svāhā"},
    { tibetan: "ཨོཾ་རཏྣཱ་ཀཱ་རཿཧྲཱིཿརཏྣཾ་དད་སྭཱ་ཧཱ།", transliteration: "oṁ ratnā kāraḥ hrīḥ ratnaṁ dé svāhā"},
    { tibetan: "ཨོཾ་ས་མནྟ་བྷ་དྲ་སཾ་སྭཱ་ཧཱ།", transliteration: "oṁ samanta bhadra saṁ svāhā"},
    { tibetan: "ཨོཾ་ཀྵི་ཏི་གརྦྷ་ཀྵིཾ་སྭཱ་ཧཱ།", transliteration: "oṁ kṣitigarbha kṣiṁ svāhā"},
    { tibetan: "ཨོཾ་མ་ཎི་བཛྲོ་ཧཱུྃ།", transliteration: "oṁ maṇi vajro hūṁ"},
    { tibetan: "ཨོཾ་མ་ཎི་དྷཱ་རི་ཧཱུྃ་ཕཊ།", transliteration: "oṁ maṇi dhāri hūṁ phaṭ"},
/**/{ tibetan: "ན་མ་སྟྲཻ་ཡ་དྷཱི་ཀཱ་ནཱཾ་ཏ་ཐཱ་ག་ཏཱ་ནཱཾ། ཨོཾ་ཨསྟ་པ་རི་བྷོ་གི་སྭཱ་ཧཱ།", transliteration: "nama straiya dhīkānāṁ tathāgatānāṁ    oṁ astapari bhogi svāhā"},
    { tibetan: "ཨོཾ་སྭ་སྟི་ཀ་མཱ་ལཱཀྵི་བི་པུ་ལ་སཾ་བྷ་བ་དྷརྨ་དྷཱ་ཏུ་གོ་ཙ་རེ་སྭཱ་ཧཱ།", transliteration: "oṁ svasti kamālākṣi bipula saṁbhawa dharmadhātu gotsaré svāhā"},
    { tibetan: "ཨོཾ་བཛྲ་ཙཎྜ་སརྦ་དུཥྚཱན་ཏ་ཀ་ཧ་ན་ད་ཧ་པ་ཙ་ཧཱུྃ་ཕཊ།", transliteration: "oṁ vajra caṇḍa sarva duṣṭēn taka hana daha patsa hūṁ phaṭ"},
    { tibetan: "ཨོཾ་སུཾ་བྷ་ནཾ་སུཾ་བྷ་ཧ་ར་ཙ་ར་མ་ཧཱ་པཱ་ཤ་མ་རུ་ཏ་ཨ་མོ་གྷ་བཛྲ་ས་ཏྭ་སྭཱ་ཧཱ།", transliteration: "oṁ suṁbhanaṁ suṁbha hara cara mahā pāśa maruta amogha vajra satva svāhā"},
    { tibetan: "ཨོཾ་མུ་ནི་མུ་ནི་སྨ་ར་སྭཱ་ཧཱ།", transliteration: "oṁ muni muni samara svāhā"},
    { tibetan: "ཨོཾ་ཨ་ཛི་ཏཉྫ་ཡ་སརྦ་ས་ཏྭ་ས་མ་ཡ་མ་ནུ་ག་ཏ་སྭཱ་ཧཱ།", transliteration: "oṁ ajitenjaya sarva satva samaya manugata svāhā"},
    { tibetan: "ཨོཾ་ཨཱ་ཧྲཱིཿསིཾ་ཧ་ནཱ་ད་ཧཱུྃ་ཕཊ།", transliteration: "oṁ ā hrīḥ siṁha nāda hūṁ phaṭ"},
    { tibetan: "ཨོཾ་པདྨ་དྷཱ་རདྷཱ་ཀི་ཧཱུྃ་ཕཊ།", transliteration: "oṁ padma dhāradhāki hūṁ phaṭ"},
    { tibetan: "ཨོཾ་པདྨ་ནི་ར་ཏེ་ཤྭ་ར་ཧྲཱིཿཧཱུྃ་ཕཊ།", transliteration: "oṁ padma nira téśwara hrīḥ hūṁ phaṭ"},
    { tibetan: "ཨོཾ་རཏྣ་ཨ་གྲ་ཨ་པྲ་ཏི་ཧ་ཏ་ཧཱུྃཿཕཊ།", transliteration: "oṁ ratna agra aprati hata hūṁ phaṭ"},
    { tibetan: "ཨོཾ་ཧྲཱིཿཏྲཻ་ལོ་ཀྱ་བི་ཛ་ཡ་ཨ་མོ་གྷ་པཱ་ཤ་ཨ་པྲ་ཏི་ཧ་ཏ་ཧྲཱིཿཧ་ཧཱུྃ་ཕཊ་སྭཱ་ཧཱ།", transliteration: "oṁ hrīḥ trailokya bijaya amoghapāśa aprati hata hrīḥ ha hūṁ phaṭ svāhā"},
    { tibetan: "ཨོཾ་ཧ་ལ་ཧ་ལ་ཧྲཱིཿཔདྨ་གརྦྷ་ཧཱུྃ་ཕཊ་སྭཱ་ཧཱ།", transliteration: "oṁ hala hala hrīḥ padma garbha hūṁ phaṭ svāhā"},
    { tibetan: "ཨོཾ་པདྨ་ཨ་ལཾ་ཀཱ་ར་ཧཱུྃ་ཕཊ།", transliteration: "oṁ padma alaṁkāra hūṁ phaṭ"},
    { tibetan: "ཨོཾ་བཛྲ་དྷརྨ་དྷཱ་ཏུ་ཧཱུྃ་སྭཱ་ཧཱ།", transliteration: "oṁ vajra dharmadhātu hūṁ svāhā"},
    { tibetan: "ཨོཾ་བྷྲཱུྃ་ཧྲཱིཿཧ་ཧཱུྃ་སྭཱ་ཧཱ།", transliteration: "oṁ bhrūṁ hrīḥ ha hūṁ svāhā"},
    { tibetan: "ཨོཾ་མ་ཎི་པདྨེ་ཧཱུྃ།", transliteration: "oṁ maṇi padmé hūṁ"},
    { tibetan: "ཨོཾ་པདྨོ་ཥྞཱ་ཥ་བི་མ་ལེ་ཧཱུྃ་ཕཊ།", transliteration: "oṁ padmo uṣṇīṣa bimalé hūṁ phaṭ"},
    { tibetan: "ཨོཾ་ཨ་མོ་གྷ་ཙིནྟ་མ་ཎི་པ་ར་ད་པདྨེ་ཛྭ་ལ་ཛྭ་ལ་ན་བྷུ་ཛེ་ཧཱུྃ།", transliteration: "oṁ amogha tsinta maṇi parada padmé jvala jvala nabhujé hūṁ"},
    { tibetan: "ཨོཾ་ཨ་མོ་གྷ་བཻ་རོ་ཙ་ན་མ་ཧཱ་མུ་དྲཱ་མ་ཎི་པདྨེ་ཛྭ་ལ་པྲ་བརྟ་ཡ་ཧཱུྃ།", transliteration: "oṁ amogha bairotsana mahā mudrā maṇi padmé jvala prabartaya hūṁ"},
    { tibetan: "ཨོཾ་ཨ་མོ་གྷ་མཎྜ་ལ་པདྨ་ཨ་བྷི་ཥེ་ཀཾ་མ་ཎི་བཛྲེ་སརྦ་ཏ་ཐཱ་ག་ཏ་ཨ་བྷི་ཥེ་ཀེ་ཧཱུྃ།", transliteration: "oṁ amogha maṇḍala padma abhiṣékaṁ maṇi vajré sarva tathāgata abhiṣéké hūṁ"},
    { tibetan: "ཨོཾ་ཨ་མོ་གྷ་པཱུ་ཛ་མ་ཎི་པདྨེ་བཛྲེ་ཏ་ཐཱ་ག་ཏ་བི་ལོ་ཀི་ཏེ་ས་མནྟ་པྲ་ས་ར་ཧཱུྃ།", transliteration: "oṁ amogha pūja maṇi padmé vajré tathāgata bilokité samanta prasara hūṁ"},
    { tibetan: "ཏདྱ་ཐཱ། ཨོཾ་མུ་ནེ་མུ་ནེ་མ་ཧཱ་མུ་ན་ཡེ་སྭཱ་ཧཱ།", transliteration: "tadyathā    oṁ muné muné mahā munayé svāhā"},
    { tibetan: "ན་མོ་བྷ་ག་ཝ་ཏེ་སརྦ་དུརྒ་ཏི་པ་རི་ཤོ་དྷ་ན་རཱ་ཛཱ་ཡ། ཏ་ཐཱ་ག་ཏཱ་ཡ། ཨརྷ་ཏེ་སམྱཀ་སཾ་བུད་དྷཱ་ཡ། ཏདྱ་ཐཱ། ཨོཾ་ཤོ་དྷ་ནེ་ཤོ་དྷ་ནེ། སརྦ་པཱ་པཾ་བི་ཤོ་དྷ་ནེ། ཤུད་དྷེ་བི་ཤུད་དྷེ། སརྦ་ཀརྨ་ཨཱ་བ་ར་ཎ་བི་ཤུད་དྷེ་སྭཱ་ཧཱ།", transliteration: "namo bhagawaté sarva durgati pariśodhana rājāya    tathāgatāya    arhaté samyak saṁbuddhāya    tadyathā    oṁ śodhané śodhané    sarva pāpaṁ biśodhané    śuddhé biśuddhé    sarva karma āvaraṇa biśuddhé svāhā"},
    { tibetan: "ཨོཾ་ཤོ་དྷ་ནེ་ཤོ་དྷ་ནེ། སརྦ་པཱ་པཾ་བི་ཤོ་དྷ་ནེ། ཤུད་དྷེ་བི་ཤུད་དྷེ། སརྦ་ཀརྨ་ཨཱ་བ་ར་ཎ་བི་ཤུད་དྷེ་སྭཱ་ཧཱ།", transliteration: "oṁ śodhané śodhané    sarva pāpaṁ biśodhané    śuddhé biśuddhé    sarva karma āvaraṇa biśuddhé svāhā"},
    { tibetan: "ན་མོ་རཏ་ཎ་ཏྲ་ཡཱ་ཡ། ཨོཾ་ཀཾ་ཀ་ནི་ཀཾ་ཀ་ནི། རོ་ཙ་ནི་རོ་ཙ་ནི། ཏྲོ་ཊ་ནི་ཏྲོ་ཊ་ནི། ཏྲཱ་ས་ནི་ཏྲཱ་ས་ནི། པྲ་ཏི་ཧ་ན་པྲ་ཏི་ཧ་ན། སརྦ་ཀརྨ་པ་རཾ་པ་རཱ་ཎི་མེ་སརྦ་ས་ཏྭ་ནཉྩ་སྭཱ་ཧཱ།", transliteration: "namo ratṇa trayāya    oṁ kaṁkani kaṁkani    rocani rocani    troṭani troṭani    trāsani trāsani    pratihana pratihana    sarva karma paraṁparā ṇimé sarva satva nentsa svāhā"},
    { tibetan: "ན་མོ་རཏྣ་ཏྲ་ཡཱ་ཡ། ན་མོ་བྷ་ག་ཝ་ཏེ། ཨ་མི་ཏ་བྷཱ་ཡ། ཏ་ཐཱ་ག་ཏཱ་ཡ། ཨརྷ་ཏེ་སམྱཀྶཾ་བུད་དྷཱ་ཡ། ཏདྱ་ཐཱ། ཨོཾ་ཨ་མི་ཏེ། ཨ་མི་ཏཱ། ཨ་མི་ཏོད་བྷ་བེ། ཨ་མི་ཏ། སཾ་བྷ་བེ། ཨ་མི་ཏ་བི་ཀྲཱནྟེ། ཨ་མི་ཏ་བི་ཀྲཱནྟ་ག་མི་ནི། ག་ག་ན་ཀཱིརྟི་ཀ་རེ་སརྦ་ཀརྨ་ཀླེ་ཤ་ཀྵ་ཡཾ་ཀ་རི་སྭཱ་ཧཱ།", transliteration: "namo ratna trayāya    namo bhagawaté    amitabhāya    tathāgatāya    arhaté samyak saṁbuddhāya    tadyathā    oṁ amité    amitā    amitot bhawé    amita    saṁbhawé    amita bikrānté    amita bikrānta gamini    gagana kīrtikaré sarva karma kléśa khayaṁ kari svāhā"},
    { tibetan: "ཨོཾ་ཨ་མི་ཏེ། ཨ་མི་ཏཱ། ཨ་མི་ཏོད་བྷ་བེ།ཨ་མི་ཏ། སཾ་བྷ་བེ། ཨ་མི་ཏ་བི་ཀྲཱནྟེ། ཨ་མི་ཏ་བི་ཀྲཱནྟ་ག་མི་ནི། ག་ག་ན་ཀཱིརྟི་ཀ་རེ་སརྦ་ཀརྨ་ཀླེ་ཤ་ཀྵ་ཡཾ་ཀ་རི་སྭཱ་ཧཱ།", transliteration: "oṁ amité    amitā    amitot bhawé amita    saṁbhawé    amita bikrānté    amita bikrānta gamini    gagana kīrtikaré sarva karma kléśa khayaṁ kari svāhā"},
    { tibetan: "ཨོཾ་རཏྣེ་རཏྣེ། མ་ཧཱ་རཏྣེ། རཏྣ་སཾ་བྷ་བེ། རཏྣ་ཀི་རཏྣེ། རཏྣ་མཱ་ལཱ། བི་ཤུད་དྷེ་ཤོདྷ་ཡ་སརྦ་པཱ་པཾ་ཧཱུྃ་ཏྲཊ།", transliteration: "oṁ ratné ratné    mahā ratné    ratna saṁbhawé    ratna ki ratné    ratna mālā    biśuddhé śodhaya sarva pāpaṁ hūṁ traṭ"},
    { tibetan: "ཨོཾ་ཨ་མོ་གྷ་ཨ་པྲ་ཏི་ཧ་ཏ། སརྦ་ཨཱ་བ་ར་ཎ། བི་ནཱ་ཤ་ནི། ཧ་ར་ཧ་ར་ཧཱུྃ་ཕཊ།", transliteration: "oṁ amogha aprati hata    sarva āvaraṇa    bināśani    hara hara hūṁ phaṭ"},
    { tibetan: "ཨོཾ་ཨ་མོ་གྷ་ཨ་པྲ་ཏི་ཧ་ཏ། སརྦ་ཨཱ་བ་ར་ཎ། བི་ཤོདྷ་ནི། ཧ་ར་ཧ་ར་ཧཱུྃ་ཕཊ།", transliteration: "oṁ amogha aprati hata    sarva āvaraṇa    biśodhani    hara hara hūṁ phaṭ"},
    { tibetan: "ཨོཾ་བཛྲ་དྷཱ་ཏཱི་ཤྭ་རཱི་སྭཱ་ཧཱ།", transliteration: "oṁ vajra dhātī śvarī svāhā"},
    { tibetan: "ཨོཾ་ལོ་ཙ་ནེ་བ་སུ་དེ་སྭཱ་ཧཱ།", transliteration: "oṁ locané basudé svāhā"},
    { tibetan: "ཨོཾ་པཱ་ཎ་ཌ་རི་བཱ་སི་ནི་བ་ར་དེ་སྭཱ་ཧཱ།", transliteration: "oṁ pāṇaḍari vāsini waradé svāhā"},
    { tibetan: "ཨོཾ་མཱ་མ་ཀཱི་ཀི་རི་ཀི་རི་སྭཱ་ཧཱ།", transliteration: "oṁ māmakī kiri kiri svāhā"},
    { tibetan: "ཨོཾ་ཏཱ་རེ་ཏུཏྟཱ་རེ་ཏུ་རེ་སྭཱ་ཧཱ།", transliteration: "oṁ tāré tuttāré turé svāhā"},
    { tibetan: "ཏདྱ་ཐཱ། ཨོཾ་ཧྲཱིཿཤུ་ཏི་སྨྲྀ་ཏི་བི་ཛ་ཡེ་སྭཱ་ཧཱ། པྲཛྙཱ་པཱ་ར་མི་ཏཱ་ཡེ་སརྦ་དུརྒ་ཏི་ཤོ་དྷ་ཡ་རཱ་ཛཱ་ཡ་སྭཱ་ཧཱ།", transliteration: "tadyathā    oṁ hrīḥ śuti smṛti bijayé svāhā    prajñā pāramitā yé sarva durgati śodhaya rājāya svāhā"},
    { tibetan: "ཨོཾ་མ་ཎི་བཛྲ་ཧྲི་ད་ཡ་བཛྲ་མཱ་ར་སིནྱ་བི་དྲ་པ་ཎི། ཧ་ན་ཧ་ན་བཛྲ་གརྦྷེ། ཏྲཱ་ས་ཡ་ཏྲཱ་ས་ཡ། སརྦ་མཱ་ར་བྷུ་བ་ནཱ་ནི་ཧཱུྃ་ཧཱུྃ། སཾ་ངྷ་ར་སཾ་དྷ་ར་བུདྡྷ་མཻ་ཏྲི་སརྦ་ཏ་ཐཱ་ག་ཏ། བཛྲ་ཀལྤ་ཨ་དྷིཥྛི་ཏེ་སྭཱ་ཧཱ།", transliteration: "oṁ maṇi vajra hridaya vajra māra sinya bidrapaṇi    hana hana vajra garbhé    trāsaya trāsaya    sarva māra bhubanāni hūṁ hūṁ    saṁhara saṁdhara buddha maitri sarva tathāgata    vajra kalpa adhiṣṭhité svāhā"},
    { tibetan: "ཨོཾ་བི་པུ་ལ་གརྦྷེ། མ་ཎི་པྲ་བྷེ། ཏ་ཐཱ་ག་ཏ་ནི་རྡེ་ཤ་ནི། མ་ཎི་མ་ཎི་སུ་པྲ་བྷེ། བི་མ་ལེ། སཱ་ག་ར་གམྦྷི་རེ་ཧཱུྃ་ཧཱུྃ། ཛྭཱ་ལ་ཛྭཱ་ལ། བུདྡྷ་བི་ལོ་ཀི་ཏེ། གུ་ཧྱ་ཨ་དྷིཥྛི་ཏེ་གརྦྷེ་སྭཱ་ཧཱ།", transliteration: "oṁ bipula garbhé    maṇi prabhé    tathāgata nirdé śani    maṇi maṇi suprabhé    bimalé    sāgara gambhiré hūṁ hūṁ    jvāla jvāla    buddha bilokité    guhya adhiṣṭhité garbhé svāhā"},
    { tibetan: "ཨོཾ་པདྨ་དྷཱ་ར་ཨ་མོ་གྷ་ཛ་ཡ་ཏེ་ཙུ་རུ་ཙུ་རུ་སྭཱ་ཧཱ།", transliteration: "oṁ padma dhāra amogha jayaté curu curu svāhā"},
    { tibetan: "ཨོཾ་བྷྲཱུྃ་སྭཱ་ཧཱ། ཨོཾ་ཨ་མྲྀ་ཏ་ཨཱ་ཡུརྡ་དེ་སྭཱ་ཧཱ།", transliteration: "oṁ bhrūṁ svāhā    oṁ amṛta āyurdadé svāhā"},
    { tibetan: "ཨོཾ་ན་མ་སྟྲཻ་ཡ་དྷཱི་ཀཱ་ནཱཾ་སརྦ་ཏ་ཐཱ་ག་ཏ་ཧྲྀ་ད་ཡ། གརྦྷེ་ཛྭ་ལ་ཛྭ་ལ་དྷརྨ་དྷཱ་ཏུ་གརྦྷེ་སཾ་བྷ་ར་མ་མ་ཨཱ་ཡུཿསཾ་ཤོ་དྷ་ཡ་སཾ་ཤོ་དྷ་ཡ། མ་མ་སརྦ་པཱ་པཾ། སརྦ་ཏ་ཐཱ་ག་ཏ་ས་མནྟོ་ཥྞཱི་ཥ་བི་མ་ལ་བི་ཤུདྡྷེ་ཧཱུྃ་ཧཱུྃ་ཧཱུྃ། ཨྃ་བྃ་སྃ་ཛཿསྭཱ་ཧཱ།", transliteration: "oṁ nama straiya dhīkānāṁ sarva tathāgata hṛdaya    garbhé jvala jvala dharmadhātu garbhé saṁbhara mama āyuḥ saṁśodhaya saṁśodhaya    mama sarva pāpaṁ    sarva tathāgata samantoṣṇīṣa bimala biśuddhé hūṁ hūṁ hūṁ    aṁ baṁ saṁ jaḥ svāhā"},
    { tibetan: "ཨོཾ་སརྦ་ཏ་ཐཱ་ག་ཏོཥྞི་ཥ་དྷཱ་ཏུ་མུ་དྲཱ་ཎཱི་སརྦ་ཏ་ཐཱ་ག་ཏ་དྷརྨ་དྷཱ་ཏུ་བི་བྷཱུ་ཥི་ཏ་ཨ་དྷིཥྛི་ཏེ་ཧུ་རུ་ཧུ་རུ་ཧཱུྃ་ཧཱུྃ་སྭཱ་ཧཱ།", transliteration: "oṁ sarva tathāgatoṣṇīṣa dhātu mudrāṇī sarva tathāgata dharmadhātu bibhūṣita adhiṣṭhité huru huru hūṁ hūṁ svāhā"},
    { tibetan: "ཨོཾ་སརྦ་ཏ་ཐཱ་ག་ཏ་བྱཱ་ར་ལོ་ཀི་ཏེ་ཛ་ཡ་ཛ་ཡ་སྭཱ་ཧཱ། ཨོཾ་ཧུ་རུ་ཧུ་རུ་ཛ་ཡ་མུ་ཁེ་སྭཱ་ཧཱ། ཨོཾ་བཛྲ་ཨཱ་ཡུ་ཥེ་སྭཱ་ཧཱ།", transliteration: "oṁ sarva tathāgatabya ralokité jaya jaya svāhā    oṁ huru huru jaya mukhé svāhā    oṁ vajra āyuṣé svāhā"},
    { tibetan: "ཨོཾ་ན་མཿས་མནྟ་བུདྡྷཱ་ནཱཾ་སརྦ་བུདྡྷ་བོ་དྷི་ས་ཏྭ་ཧྲྀ་ད་ཡཾ་ནི་བི་ཤ་ནི་ནི་མཿ སརྦ་བིརྱཱ་སྭཱ་ཧཱ།", transliteration: "oṁ namaḥ samanta buddhānāṁ sarva buddha bodhisatva hṛdayaṁ niviśa ninimaḥ    sarva biryā svāhā"},
    { tibetan: "ན་མཿསརྦ་ཏ་ཐཱ་ག་ཏ་ཧྲྀ་ད་ཡ་ཨ་ནུ་ག་ཏེ། ཨོཾ་ཀུ་རུཾ་གི་ནི་སྭཱ་ཧཱ།", transliteration: "namaḥ sarva tathāgata hṛdaya anugaté    oṁ kuruṁ gini svāhā"},
    { tibetan: "ཨོཾ་ཨཱཿལི་ཀཱ་ལི་ཛྙཱ་ན་པཉྩ་སཏྭ་ཀྲོ་ཏ་མུ་ན་ཡེ་སྭཱ་ཧཱ།", transliteration: "oṁ āḥli kāli jñāna panca satva krota munayé svāhā"},
    { tibetan: "ཨོཾ་ཨཱཿཧཱུྃ་བཛྲ་མ་ཧཱ་གུ་རུ་སརྦ་སིདྡྷི་ཧཱུྃ༔", transliteration: "oṁ āḥ hūṁ vajra mahā guru sarva siddhi hūṁ"},
    { tibetan: "ཨོཾ་བྷོ་དྷི་ཙིཏྟ་མ་ཧཱ་སུ་ཁ་ཛྙཱ་ན་དྷཱ་ཏུ་ཨཱཿ", transliteration: "oṁ bhodhicitta mahā sukha jñāna dhātu āḥ"},
    { tibetan: "ཨོཾ་རུ་ལུ་རུ་ལུ་ཧཱུཾ་བྷྱོ་ཧཱུྃ།", transliteration: "oṁ rulu rulu hūṁ bhyo hūṁ"},
    { tibetan: "ཨ་ཧ་རི་ནི་ས་ཧཱུྃ།", transliteration: "a ha ri ni sa hūṁ"},
    { tibetan: "ཨོཾ་ཨཱཿཔྲཛྙཱ་དྷྲྀ་ཀ་ཧཱ་ཧཱུྃ།", transliteration: "oṁ āḥ prajñā dhṛka hā hūṁ"},
    { tibetan: "ཨོཾ་ཨཱཿཧཱུྃ་ཧྲཱིཿ ཨོཾ་མ་ཎི་པདྨེ་ཧཱུྃ། ཨོཾ་བཻ་རོ་ཙ་ན་ཧཱུྃ་ཨཀྵོ་བྷྱ། རཏྣ་སམྦྷ་ཝཿ ཨ་མི་དྷེ་ཝཿཨ་མོ་གྷ་སིདྡྷི་ཧཱུྃ། ཨོཾ་པདྨ་ཧསྟ་མ་ཧཱ་ཨ་མོ་གྷ་པཱ་ཤ་སཱ་དྷ་ཡ་ས་མ་ཡ་ཧྲྀ་ད་ཡཱཾ་ཙ་ར་ཙ་ར་ཧཱུྃ༔ ན་མོ་བྷ་ག་ཝ་ཏེ་ཨཱརྱ་ཨ་ཝ་ལོ་ཀི་ཏེ་ཤྭ་རཱ་ཡ། བོ་དྷི་སཏྭ་ཡ་མ་ཧཱ་སཏྭ་ཡ་མ་ཧཱ་ཀ་རུ་ཎི་ཀཱ་ཡ༔ སིདྡྷི་མནྟྲ་ཡ་ཡ་ནི་སྭཱ་ཧཱ།", transliteration: "oṁ āḥ hūṁ hrīḥ    oṁ maṇi padmé hūṁ    oṁ bairotsana hūṁ akṣobhya    ratna sambhawaḥ    amidhéwaḥ amogha siddhi hūṁ    oṁ padma hasta mahā amoghapāśa sādhaya samaya hṛdayāṁ cara cara hūṁ    namo bhagawaté ārya avalokitéśvarāya    bodhisatvaya mahāsatvaya mahā karuṇikāya    siddhi mantraya yani svāhā"},
    { tibetan: "ན་མ་སྟྲཻ་ཡ་དྷཱི་ཀཱ་ནཱཾ་སརྦ་ཏ་ཐཱ་ག་ཏེ་བྷྱ༔ ཨརྷ་ཏེ་བྷྱཿ སམྱ་ཀྶཾ་བུདྡྷེ་བྷྱཿ ཏདྱ་ཐཱ། ཨོཾ་ཀུ་མ་རཱུ་བི་དྷཱ་ར་ཎཱི། བི་ཤྭ་སཾ་བྷ་བ། ཨཱ་གཙྪ་ཨཱ་གཙྪ། ལ་ཧུ་ལ་ཧུ། བྷྲཱུྃ་བྷྲཱུྃ། ཧཱུྃ་ཧཱུྃ། ཛི་ན་ཛིཀ །མཉྫུ་ཤྲཱི་ཡེ། སུ་ཤྲཱི་ཡེ། ཏཱ་ར་ཡ་མཱྃ། སརྦ་དུ་ཁེ་བྷྱཿཕཊ་ཕཊ། ཤ་མ་ཡ་ཤ་མ་ཡ། ཨམྲྀ་ཏོདྦྷ་པ། ཨུ་ཏ་བྷ་ཝེ། སརྦ་པཱ་པཾ་མེ་ནཱ་ཤ་ཡ་སྭཱ་ཧཱ།", transliteration: "nama straiya dhīkānāṁ sarva tathāgaté bhyaḥ    arhaté bhyaḥ    samyak saṁbuddhé bhyaḥ    tadyathā    oṁ kumarū bidhāraṇī    biśva saṁbhawa    āgantsa āgantsa    lahu lahu    bhrūṁ bhrūṁ    hūṁ hūṁ    jina jik    mañjuśrīyé    suśrīyé    tārayamāṁ    sarva dukhé bhyaḥ phaṭ phaṭ    śamaya śamaya    amṛtod bhawa    utabhawé    sarva pāpaṁ ménāśaya svāhā"},
    { tibetan: "ན་མ་སྟྲཻ་ཡ་དྷཱི་ཀཱ་ནཱཾ་ཏ་ཐཱ་ག་ཏཱ་ནཱཾ་སརྦ་ཏྲཱ་པྲ་ཏི་ཧ་ཏཱ་བཱ་པྟི། དྷརྨ་ཏཱ་བཱ་སི་ནཱཾ། ཨཾ་ཨ། ས་མ་ས་མ་ས་མནྟ་ཏོ། ཨཱ་ནནྟཱ་པཱ་པྟི་ཤཱ་ས་ནི་ཧ་ར་ཧ་ར་སྨ་ར་སྨ་ར་ཎི་བི་ག་ཏ་རཱ་ག་བུད་དྷ་དྷརྨ་ཏེ། ས་ར་ས་ར་ས་མ་བ་ལ་ཧ་ས་ཧ་ས། ཏྲ་ཡ་ཏྲ་ཡ། ག་ག་ན་མ་ཧཱ་བ་ར་ཎ་ལ་ཀྵ་ཎེ་ཛྭཱ་ལ་ཛྭཱ་ལ་ན་སཱ་ག་རེ་སྭཱ་ཧཱ།", transliteration: ""},
    { tibetan: "ན་མཿསརྦ་བུདྡྷ་བོ་དྷི་ས་ཏྭཱ་ནཱཾ་པ་ར་པ་ར། སརྦཾ་སརྦཾ། ས་མ་ས་མ། ཀཱ་རུ་ཎཱཾ་ཀཱ་རུ་ཎཱཾ། ཏཱ་རཱ་ཏཱ་རཱ། སཱ་རཱ་སཱ་རཱ། ཨ་ཏཱི་ཨ་ཏཱི། ཨཱ་མཱི་ཏཱཾ་ཨཱ་མཱི་ཏཱཾ། ཨ་ཏཱི་ཨ་ཏཱི། བཱི་རཱཾ་བཱི་རཱཾ། ཨཱ་ཏཱི་ཨཱ་ཏཱི། ཤཱུ་རཾ་ཤཱུ་རཾ། ཧ་ཧ་ཧ་ཧ། མ་ཧཱ་ས་མ་ཡ། ན་མཿཏྲ། ཨ་མ་ལ་སིདྡྷི་དཱ་ཡ་ཀེ་བྷྱཿ སརྦ་བུ་དྡྷ་བོ་དྷི་ས་ཏྭ་བྷྱཿ སརྦ་ཨ་ནནྟ་མ། དྷྱེ་བྷྱཿམ་ཧཱ་ཀཱ་རུ་ཎཱི། མཱ་ལཱི་ནཱི། ཏྲི་ས་མ་ཡེ་ཛྭ་ལ་སྭཱ་ཧཱ།", transliteration: ""},
    { tibetan: "ཨོཾ་བཛྲ་སཏྭ་ས་མ་ཡ་མ་ནུ་པཱ་ལ་ཡ། བཛྲ་ས་ཏྭ་ཏྭེ་ནོ་པ་ཏིཥྛ་དྲྀ་ཌྷོ་མེ་བྷ་ཝ། སུ་ཏོ་ཥྱོ་མེ་བྷ་ཝ། ཨ་ནུ་རཀྟོ་མེ་བྷ་ཝ། སུ་པོ་ཥྱོ་མེ་བྷ་ཝ། སརྦ་སིདྡྷི་མྨེ་པྲ་ཡཙྪ། སརྦ་ཀརྨ་སུ་ཙ་མེ། ཙིཏྟཾ་ཤྲེ་ཡཿཀུ་རུ་ཧཱུྃ། ཧ་ཧ་ཧ་ཧ་ཧོ། བྷ་ག་ཝཱན། སརྦ་ཏ་ཐཱ་ག་ཏ། བཛྲ་མ་མེ་མུཉྩ། བཛྲཱི་བྷ་ཝ་མ་ཧཱ་ས་མ་ཡ་སཏྭ་ཨཱ།", transliteration: ""},
    { tibetan: "ཨོཾ་ཨ་ཨཱ་ཨི་ཨཱི་ཨུ་ཨཱུ་རྀ་རཱྀ་ལྀ་ལཱྀ་ཨཻ་ཨཻ་ཨོ་ཨཽ་ཨཾ་ཨཿསྭཱ་ཧཱ།", transliteration: ""},
    { tibetan: "ཨོཾ་ཀ་ཁ་ག་གྷ་ང༌། ཙ་ཚ་ཛ་ཛྙ་ཉ། ཊ་ཋ་ཌ་ཌྷ་ཎ། ཏ་ཐ་ད་དྷ་ན། པ་ཕ་བ་བྷ་མ། ཡ་ར་ལ་ཝ། ཤ་ཥ་ས་ཧ་ཀྵ་སྭཱ་ཧཱ།", transliteration: ""},
    { tibetan: "ཨོཾ་ཡེ་དྷརྨྨ་ཧེ་ཏུ་པྲ་བྷ་ཝཱ་ཧེ་ཏུནྟེ་ཥཱནྟ་ཐཱ་ག་ཏོ་ཧྱ་ཝ་དཏ། ཏེ་ཥཱཉྩ་ཡོ་ནི་རོ་དྷ་ཨེ་ཝཾ་བཱ་དཱི་མ་ཧཱ་ཤྲ་མ་ཎཿསྭཱ་ཧཱ།", transliteration: ""},

    ]
})